/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/mango_export.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/mango_export.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" position={[-0.009, 0.514, -0.044]} rotation={[0, Math.PI / 6, -Math.PI]}>
          <mesh name="MANGO_PEELIING" geometry={nodes.MANGO_PEELIING.geometry} material={materials['Material.007']} position={[-0.003, 0.01, 0]} scale={0.937} />
        </group>
        <group name="Empty001" position={[0.019, 0.411, -0.044]} rotation={[0, Math.PI / 6, -Math.PI]}>
          <group name="MANGO_LEAF" position={[-0.169, 0.149, -0.014]} rotation={[2.958, -1.265, 2.963]} scale={0.589}>
            <mesh name="Mesh_25001" geometry={nodes.Mesh_25001.geometry} material={materials['Material.004']} />
            <mesh name="Mesh_25001_1" geometry={nodes.Mesh_25001_1.geometry} material={materials['Mossy Weathered Wood.001']} />
          </group>
          <mesh name="MANGO_MID" geometry={nodes.MANGO_MID.geometry} material={materials['Tree Bark With Moss.001']} position={[-0.016, 0.189, 0.022]} rotation={[-2.99, -1.266, -2.983]} scale={0.589} />
        </group>
        <mesh name="MANGO_baked" geometry={nodes.MANGO_baked.geometry} material={materials['Material.006']} morphTargetDictionary={nodes.MANGO_baked.morphTargetDictionary} morphTargetInfluences={nodes.MANGO_baked.morphTargetInfluences} position={[-0.009, 0.515, -0.044]} rotation={[0, Math.PI / 6, -Math.PI]} />
      </group>
    </group>
  )
}

useGLTF.preload('/mango_export.glb')
